server:
  port: 2000
  servlet:
    context-path: /music

spring:
  application:
    name: music
  #    main:
  #      allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=music_app
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: 'org.postgresql.Driver'
    hikari:
      maximumPoolSize: 120
      idleTimeout: 300000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
      schema: ${spring.application.name}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        time_zone: Asia/Ho_Chi_Minh
    open-in-view: false
